name: ci/cd
on: 
  push:
      branches: ["main"]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: pulling
        uses: actions/checkout@v3
      
      - name: docker image build
        run: docker build -t cr.yandex/${{ secrets.YC_REGISTRY_ID }}/profile-app .
      
      - name: docker login
        uses: docker/login-action@v3.0.0
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.YC_KEYS }}
      - name: pushing
        run: docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/profile-app:latest
